language: cpp

matrix:
    include:

        ############ Linux build ############################

        - name: Linux build
          stage: build
          os: linux # Defaults to Ubuntu 16.04 at the time of writing - use `dist` to specify a different dist

          before_install:
              - sudo apt update -y
              #- sudo apt install -y build-essential cmake git gcc g++ libcurl4-openssl-dev libssl-dev make pkg-config tar wget zlib1g-dev
              - sudo apt install -y build-essential cmake git gcc g++ libcurl4-openssl-dev make pkg-config tar wget zlib1g-dev
              - sudo apt install -y tree # This is not required

              # # Install cmake
              # - gzipFilename="cmake-3.12.4-Linux-x86_64"
              # - wget -q "https://cmake.org/files/v3.12/$gzipFilename.tar.gz"
              # - tar -xzf "$gzipFilename.tar.gz"
              # - mv "$gzipFilename" cmake
              # - sudo mv cmake /usr/local/bin
              # - export PATH="$PATH:/usr/local/bin/cmake/bin"
              #
              # #- sudo apt install -y cmake3 git gcc g++ make pkg-config tar wget zlib1g-dev
              # - sudo apt install -y git gcc g++ make pkg-config tar wget zlib1g-dev

          script:
              - pwd

              # Create GCSSDK_3RDPARTY_HOME
              - export GCSSDK_3RDPARTY_HOME="$HOME/Workspace/thirdparty/gcssdk"
              - mkdir -p "$GCSSDK_3RDPARTY_HOME"

              # Build OpenSSL-1.0.2 from source
              - pushd .
              - mkdir -p "$HOME/Downloads"
              - cd $HOME/Downloads
              #- wget -q https://www.openssl.org/source/openssl-1.0.2n.tar.gz
              - wget -q https://www.openssl.org/source/openssl-1.0.2j.tar.gz
              - tar xf openssl-1.0.2j.tar.gz
              - cd $HOME/Downloads/openssl-1.0.2j
              #- ./config --shared # TODO Should build static libs
              - ./config --prefix="$GCSSDK_3RDPARTY_HOME/ssl" --openssldir="$GCSSDK_3RDPARTY_HOME/openssl"
              - make -j ${NCPU:-4}
              #- sudo make install
              - make install
              - popd

              # Build crc32c from source
              - pushd .
              - cd $HOME/Downloads
              - wget -q https://github.com/google/crc32c/archive/1.0.6.tar.gz
              - tar -xf 1.0.6.tar.gz
              - cd $HOME/Downloads/crc32c-1.0.6
              - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=yes -DCRC32C_BUILD_TESTS=OFF -DCRC32C_BUILD_BENCHMARKS=OFF -DCRC32C_USE_GLOG=OFF -H. -Bcmake-out/crc32c
              - sudo cmake --build cmake-out/crc32c --target install -- -j ${NCPU:-4}
              - sudo ldconfig
              - popd

              # Build Protobuf from source
              - pushd .
              - cd $HOME/Downloads
              - wget -q https://github.com/google/protobuf/archive/v3.6.1.tar.gz
              - tar -xf v3.6.1.tar.gz
              - cd $HOME/Downloads/protobuf-3.6.1/cmake
              - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=yes -Dprotobuf_BUILD_TESTS=OFF -H. -Bcmake-out
              - sudo cmake --build cmake-out --target install -- -j ${NCPU:-4}
              - sudo ldconfig
              - popd

              # Build c-ares from scratch
              - pushd .
              - sudo apt install -y automake libtool
              - cd $HOME/Downloads
              - wget -q https://github.com/c-ares/c-ares/archive/cares-1_14_0.tar.gz
              - tar -xf cares-1_14_0.tar.gz
              - cd $HOME/Downloads/c-ares-cares-1_14_0
              - ./buildconf && ./configure && make -j ${NCPU:-4}
              - sudo make install
              - sudo ldconfig
              - popd

              # Build gRPC from source
              - pushd .
              - cd $HOME/Downloads
              - wget -q https://github.com/grpc/grpc/archive/v1.19.1.tar.gz
              - tar -xf v1.19.1.tar.gz
              - cd $HOME/Downloads/grpc-1.19.1
              - make -j ${NCPU:-4}
              - sudo make install
              - sudo ldconfig
              - popd

              # Build googleapis from scratch
              - pushd .
              - cd $HOME/Downloads
              - wget -q https://github.com/googleapis/cpp-cmakefiles/archive/v0.1.3.tar.gz
              - tar -xf v0.1.3.tar.gz
              - cd $HOME/Downloads/cpp-cmakefiles-0.1.3
              - cmake -DBUILD_SHARED_LIBS=YES -H. -Bcmake-out
              - sudo cmake --build cmake-out --target install -- -j ${NCPU:-4}
              - sudo ldconfig
              - popd

              # Build googletest from source
              - pushd .
              - cd $HOME/Downloads
              - wget -q https://github.com/google/googletest/archive/b6cd405286ed8635ece71c72f118e659f4ade3fb.tar.gz
              - tar -xf b6cd405286ed8635ece71c72f118e659f4ade3fb.tar.gz
              - cd $HOME/Downloads/googletest-b6cd405286ed8635ece71c72f118e659f4ade3fb
              - cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_SHARED_LIBS=yes -H. -Bcmake-out
              - sudo cmake --build cmake-out --target install -- -j ${NCPU:-4}
              - sudo ldconfig
              - popd

              - openssl version
              - tree -L 2 "$GCSSDK_3RDPARTY_HOME/ssl"
              - tree -L 4 "$GCSSDK_3RDPARTY_HOME/ssl/lib"
              - ls -la "$GCSSDK_3RDPARTY_HOME/ssl/lib/pkgconfig"
              - cmake --version

              # Build gcs
              # TODO Build with static openssl libs

              # These are the default openssl out dirs - may need to change these
              # These env vars are set so cmake knows where to find the libs
              # - export OPENSSL_ROOT_DIR=/usr/local/ssl
              # - export PKG_CONFIG_PATH=/usr/local/ssl/lib/pkgconfig

              # These are my custom openssl out dirs (see above for defaults)
              - export OPENSSL_ROOT_DIR="$GCSSDK_3RDPARTY_HOME"/ssl
              - export PKG_CONFIG_PATH="$GCSSDK_3RDPARTY_HOME"/ssl/lib/pkgconfig
              - ls "$OPENSSL_ROOT_DIR"
              - ls "$PKG_CONFIG_PATH"

              # Actually build gcs
              - export VERBOSE=1
              - cmake -H. -Bcmake-out -DBUILD_TESTING=OFF -DCMAKE_VERBOSE_MAKEFILE=ON
              # The 'super' project downloads things, which I think we want to avoid
              # - or do we only want to avoid ssl, and download everything else?
              #- cmake -Hsuper -Bcmake-out -DBUILD_TESTING=OFF -DCMAKE_VERBOSE_MAKEFILE=ON
              - cmake --build cmake-out -- -j ${NCPU:-4}

              - ls
              - ls -la cmake-out
              - ls cmake-out/external/curl/src/curl_project-stamp/curl_project-build-*.log
              - ls -la cmake-out/build
              - ls -la cmake-out/build/google-cloud-cpp

          after_success:
              echo "Build successful"

        ############ Mac build ##############################

        - name: Mac build
          stage: build
          os: osx

          before_install:
              #brew install curl cmake libressl c-ares
              - brew install curl libressl c-ares

          script:
              - pwd
              - cmake --version

              - export OPENSSL_ROOT_DIR=/usr/local/opt/libressl
              #- cmake -H. -Bcmake-out -DBUILD_TESTING=OFF
              - cmake -Hsuper -Bcmake-out -DBUILD_TESTING=OFF
              - cmake --build cmake-out -- -j ${NCPU:-4}

              - ls
              - ls -la cmake-out
              - ls -la cmake-out/build

          after_success:
              echo "Build successful"
